# Generated by Django 3.2.6 on 2021-10-30 05:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.PositiveIntegerField()),
                ('conta', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('CEP', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='O CEP necessita ter 8 caracteres!', regex='^.{8}$')])),
                ('estado', models.CharField(choices=[('AC', 'Acre - AC'), ('AL', 'Alagoas - AL'), ('AP', 'Amapá - AP'), ('AM', 'Amazonas - AM'), ('BA', 'Bahia - BA'), ('CE', 'Ceará - CE'), ('DF', 'Distrito Federal - DF'), ('ES', 'Espírito Santo - ES'), ('GO', 'Goiás - GO'), ('MA', 'Maranhão - MA'), ('MT', 'Mato Grosso - MT'), ('MS', 'Mato Grosso do Sul - MS'), ('MG', 'Minas Gerais - MG'), ('PA', 'Pará - PA'), ('PB', 'Paraíba - PB'), ('PR', 'Paraná - PR'), ('PE', 'Pernambuco - PE'), ('PI', 'Piauí - PI'), ('RJ', 'Rio de Janeiro - RJ'), ('RN', 'Rio Grande do Norte - RN'), ('RS', 'Rio Grande do Sul - RS'), ('RO', 'Rondônia - RO'), ('RR', 'Roraima - RR'), ('SC', 'Santa Catarina - SC'), ('SP', 'São Paulo - SP'), ('SE', 'Sergipe - SE'), ('TO', 'Tocantins - TO')], max_length=19)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField()),
                ('complemento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, default='', editable=False)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=9)),
                ('tipo', models.CharField(choices=[('ator', 'Ator'), ('figuracao', 'Figuração'), ('modelo', 'Modelo'), ('crianca', 'Criança')], max_length=9)),
                ('nome_completo', models.CharField(max_length=200)),
                ('nome_artistico', models.CharField(max_length=200)),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)])),
                ('DRT', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='nomatch', message='O DRT necessita ter 7 caracteres!', regex='^.{7}$')])),
                ('altura', models.FloatField()),
                ('manequim', models.PositiveIntegerField()),
                ('sapato', models.PositiveIntegerField()),
                ('foto3x4', models.ImageField(upload_to='3x4/')),
                ('foto_corpo_inteiro', models.ImageField(upload_to='corpo_inteiro/')),
                ('foto_com_sorriso', models.ImageField(upload_to='com_sorriso /')),
                ('CNH', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='A CNH necessita ter 11 caracteres!', regex='^.{11}$')])),
                ('veiculo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('trator', 'Trator'), ('jetski', 'JetSki')], max_length=6)),
                ('portfolio', models.URLField()),
                ('peso', models.IntegerField()),
                ('RG', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='O RG necessita ter 10 caracteres!', regex='^.{10}$')])),
                ('CPF', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='O CPF necessita ter 11 caracteres!', regex='^.{11}$')])),
                ('terno', models.PositiveIntegerField(null=True)),
                ('camisa', models.PositiveIntegerField(null=True)),
                ('busto', models.PositiveIntegerField(null=True)),
                ('cintura', models.PositiveIntegerField(null=True)),
                ('quadril', models.PositiveIntegerField(null=True)),
                ('data_nascimento', models.DateField()),
                ('habilidades', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dados_bancarios', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='casting.dadosbancarios')),
                ('endereco', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='casting.endereco')),
            ],
        ),
    ]
