# Generated by Django 3.2.6 on 2021-10-30 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadosbancarios',
            options={'verbose_name_plural': 'Dados Bancários'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='CNH',
            field=models.IntegerField(blank=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='A CNH necessita ter 11 caracteres!', regex='^.{11}$')]),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='DRT',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(code='nomatch', message='O DRT necessita ter 7 caracteres!', regex='^.{7}$')]),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='altura',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='busto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='camisa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cintura',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto3x4',
            field=models.ImageField(upload_to='static/images/3x4/'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto_com_sorriso',
            field=models.ImageField(upload_to='static/images/com_sorriso /'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto_corpo_inteiro',
            field=models.ImageField(upload_to='static/images/corpo_inteiro/'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='habilidades',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='manequim',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='peso',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='quadril',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sapato',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='terno',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='veiculo',
            field=models.CharField(blank=True, choices=[('carro', 'Carro'), ('moto', 'Moto'), ('trator', 'Trator'), ('jetski', 'JetSki')], max_length=6),
        ),
    ]
