# Generated by Django 3.2.6 on 2021-10-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0002_auto_20211030_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='foto3x4',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='foto_com_sorriso',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='foto_corpo_inteiro',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='<django.db.models.fields.SlugField>-3x4',
            field=models.ImageField(null=True, upload_to='static/images/3x4/'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='<django.db.models.fields.SlugField>-com_sorriso',
            field=models.ImageField(null=True, upload_to='static/images/com_sorriso/'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='<django.db.models.fields.SlugField>-corpo_inteiro',
            field=models.ImageField(null=True, upload_to='static/images/corpo_inteiro/'),
        ),
    ]
