# Generated by Django 3.2.6 on 2021-10-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0005_auto_20211030_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto3x4',
            field=models.ImageField(null=True, upload_to='static/images/None/3x4/'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto_com_sorriso',
            field=models.ImageField(null=True, upload_to='static/images/None/com_sorriso/'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto_corpo_inteiro',
            field=models.ImageField(null=True, upload_to='static/images/None/corpo_inteiro/'),
        ),
    ]
