# Generated by Django 3.2.6 on 2021-11-13 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0007_auto_20211030_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='CNH',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='A CNH necessita ter 11 caracteres!', regex='^.{11}$')]),
        ),
    ]
